# Generated by Django 4.1.7 on 2023-03-08 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=75)),
                ('core_competence', models.CharField(max_length=60)),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('kg', 'Kyrgyz'), ('tr', 'Turkish'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch')], max_length=2)),
                ('website', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='profile_photos/')),
                ('promotions', models.BooleanField(default=True)),
                ('course_recommendations', models.BooleanField(default=True)),
                ('helpful_resources', models.BooleanField(default=True)),
                ('teacher_announcements', models.BooleanField(default=True)),
                ('receive_promotional_emails', models.BooleanField(default=True)),
                ('unsubscribe', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(max_length=50)),
                ('card_brand', models.CharField(max_length=50)),
                ('card_last4', models.CharField(max_length=4)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_cabinet.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=75)),
                ('core_competence', models.CharField(max_length=60)),
                ('biography', models.CharField(max_length=60)),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('kg', 'Kyrgyz'), ('tr', 'Turkish'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch')], max_length=2)),
                ('photo', models.ImageField(blank=True, height_field='image_height', null=True, upload_to='mentor_profile_photo/', width_field='image_width')),
                ('website', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
