# Generated by Django 4.1.7 on 2023-03-09 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_cabinet', '0002_alter_mentorprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='show_courses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='show_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_courses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='biography',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_mentor': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
