# Generated by Django 4.1.7 on 2023-02-19 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
