# Generated by Django 4.1.6 on 2023-02-08 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activation_code',
            field=models.UUIDField(verbose_name=uuid.UUID('10ccfb06-4828-4b73-8b4b-a7068711879b')),
        ),
    ]
