# Generated by Django 4.1.6 on 2023-02-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_code_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
    ]
