# Generated by Django 4.1.6 on 2023-02-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_code_remove_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
