# Generated by Django 4.1.6 on 2023-02-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.CharField(default=0, max_length=50, verbose_name='experience'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_mentor',
            field=models.BooleanField(default=False, verbose_name='is_mentor'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(default=True, max_length=100, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='answer',
            field=models.CharField(blank=True, choices=[('в настоящий момент нет', 'в настоящий момент нет'), ('у меня маленькая аудитория', 'у меня маленькая аудитория'), ('у меня достаточная аудитория', 'у меня достаточная аудитория')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.SlugField(max_length=100, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='answer',
            field=models.CharField(choices=[('лично, частным образом', 'лично, частным образом'), ('лично, профессионально', 'лично, профессионально'), ('онлайн', 'онлайн'), ('другое', 'другое')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
