# Generated by Django 4.1.6 on 2023-02-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_experience_customuser_is_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='answer',
            field=models.CharField(blank=True, choices=[('в настоящий момент нет', 'в настоящий момент нет'), ('у меня маленькая аудитория', 'у меня маленькая аудитория'), ('у меня достаточная аудитория', 'у меня достаточная аудитория')], default=True, max_length=50, null=True),
        ),
    ]
