# Generated by Django 4.1.6 on 2023-02-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_classroom_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaching',
            name='user',
        ),
    ]
