# Generated by Django 4.1.6 on 2023-02-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_teaching_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='user',
        ),
    ]
