# Generated by Django 4.1.7 on 2023-02-19 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='is_mentor', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('lang', models.CharField(choices=[('aa', 'Afar'), ('ab', 'Abkhazian'), ('ae', 'Avestan'), ('kg', 'Kyrgyzstan'), ('eng', 'English'), ('rus', 'Russian')], max_length=3)),
                ('level', models.CharField(choices=[('BG', 'BEGGINING'), ('MD', 'MIDDLE'), ('PR', 'PROFESSIONAL'), ('ALL', 'ALL')], max_length=3)),
                ('sub_category', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='image/')),
                ('video', models.FileField(null=True, upload_to='video/')),
                ('price', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseItemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lectures/videos')),
                ('link', models.URLField(blank=True, null=True)),
                ('courseitem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseitem')),
            ],
        ),
    ]
